/*
 * This source file was generated by the Gradle 'init' task
 */
package org.soc.sonices;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import javax.sound.midi.*;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.Properties;
import java.util.concurrent.TimeUnit;

import static java.time.Instant.ofEpochMilli;

public class SonicESApp {
    private static Logger LOGGER = LogManager.getLogger(SonicESApp.class);

    private static final String CONFIGFILE = "sonices.conf";

    public static void main(String[] args) throws InvalidMidiDataException, InterruptedException, IOException, MidiUnavailableException {
        MidiHandler mh = new MidiHandler("Bus 1");
        Sequencer sequencer = MidiSystem.getSequencer(false);
        sequencer.getTransmitter().setReceiver(mh.receiver);

        // query part
        Properties configuration = new Properties();
        try {
            configuration.load(new FileInputStream(CONFIGFILE));
        } catch (IOException e) {
            LOGGER.error("Cannot read configuration file" + CONFIGFILE + ", aborting...");
            System.exit(1);
        }

        ESClient client = new ESClient(configuration);
        Sequence sequence = new Sequence(Sequence.SMPTE_25, 40);

        long now = System.currentTimeMillis();
        long start = now - TimeUnit.MINUTES.toMillis(1);
        LOGGER.info("Getting log level data from " + ofEpochMilli(start) + " to " + ofEpochMilli(now));

        LogLevelSketches.mapToDensity(LogLevelSketches.queryForLogLevels(client, "WARN", now, start), sequence, new Note(69, 0, 93));
        LogLevelSketches.mapToDensity(LogLevelSketches.queryForLogLevels(client, "DEBUG", now, start), sequence, new Note(52, 1, 70));

        sequencer.setSequence(sequence);
        LOGGER.info("start sequence");
        sequencer.open();
        sequencer.start();
        Thread.sleep(65 * 1000);
        LOGGER.info("stop sequence");
        sequencer.close();
        mh.close();

        System.exit(0);
    }
}
