/*
 * This source file was generated by the Gradle 'init' task
 */
package org.soc.sonices;

import javax.sound.midi.InvalidMidiDataException;

public class SonicESApp {

    public static void main(String[] args) throws InvalidMidiDataException, InterruptedException {
        MidiHandler mh = null;
        try {
            // open midi target device here, configure to match your device, e.g. list devices using
            // MidiDeviceDisplay utility in this package
            mh = new MidiHandler("Bus 1");
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }

        mh.send(40, 93, 300);
        mh.send(60, 93, 100);
        mh.send(45, 93, 3000);
        while (mh.messagesPending() > 0) {
            // busy wait
            Thread.sleep(500);
        }
        mh.close();
        System.exit(0);
    }
}
